spring:
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # ==== 페이징 할 때 기본값, 20개씩 조회 ==== #
  data:
    web:
      pageable:
        default-page-size: 5
  # ==== S3 파일 업로드 용량 설정 ==== #
  servlet:
    multipart:
      max-file-size: 3MB # 업로드 파일 크기 제한
      max-request-size: 5MB # 업로드 파일 크기 총량 제한
  # ==== 외부 설정파일 주입 ==== #
  config:
    import:
      - aws-s3.yml

logging.level:
  org.hibernate.SQL: debug

---

spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

---

spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dasibom-prac?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin


